const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const assert = require('node:assert/strict')
const ts = require('typescript')
// Transpile app modules without Next runtime; exercise a real isolated SQLite DB.
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true } }).outputText, filename)
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'tracking-test-'))
process.env.TURSO_DATABASE_URL = 'file:' + path.join(temp, 'test.db')
const { db, initDb } = require('../lib/db.ts')
const { ingestOrder } = require('../lib/orders.ts')
const { enqueueCapi, flushCapiQueue } = require('../lib/capi.ts')
const { getSummary, buildRange } = require('../lib/metrics.ts')
const { parseAdRef } = require('../lib/utm.ts')
async function main() {
  await initDb()
  await db.execute("INSERT INTO dashboards (id,name) VALUES ('test','Test')")
  const order = { externalId: 'order-1', status: 'paid', grossCents: 2000, netCents: 1800, utms: {}, createdAt: '2026-09-19T12:00:00.000Z', approvedAt: '2026-09-21T01:00:00.000Z', items: [{ productName: 'Principal', quantity: 1, priceCents: 1500 }, { productName: 'Bump', quantity: 1, priceCents: 500, isBump: true }] }
  await ingestOrder('test', 'generic', order, order)
  await ingestOrder('test', 'generic', { ...order, status: 'waiting_payment', grossCents: 0, netCents: 0, items: [] }, {})
  let saved = (await db.execute('SELECT * FROM orders')).rows[0]
  assert.equal(saved.status, 'paid'); assert.equal(saved.net_cents, 1800)
  await ingestOrder('test', 'generic', { ...order, items: [] }, {})
  assert.equal((await db.execute('SELECT * FROM order_items')).rows.length, 2)
  const summary = await getSummary('test', buildRange('2026-09-20', '2026-09-20', -3))
  assert.equal(summary.revenue, 1800); assert.equal(summary.byDay[0].day, '2026-09-20')
  assert.equal(summary.byHour[0].hour, 22)
  assert.equal(summary.byProduct.reduce((sum, p) => sum + Number(p.revenue), 0), 1800)
  assert.equal(summary.hasSpendData, false)
  assert.equal(parseAdRef({}).trafficSource, 'unattributed')
  assert.doesNotThrow(() => parseAdRef({ utm_content: 'Oferta 50%|12345678' }))
  await db.execute("INSERT INTO pixels (id,dashboard_id,name) VALUES ('pixel','test','Test')")
  const event = { eventName: 'Purchase', eventId: 'order-1', eventTime: 1 }
  await Promise.all([enqueueCapi('test', 'pixel', event), enqueueCapi('test', 'pixel', event)])
  assert.equal((await db.execute('SELECT * FROM capi_queue')).rows.length, 1)
  await flushCapiQueue()
  assert.notEqual((await db.execute('SELECT * FROM capi_queue')).rows[0].status, 'sent')
  await ingestOrder('test', 'generic', { ...order, status: 'refunded', items: [] }, {})
  await ingestOrder('test', 'generic', order, {})
  saved = (await db.execute('SELECT * FROM orders')).rows[0]
  assert.equal(saved.status, 'refunded')
  assert.equal((await getSummary('test', buildRange('2026-09-20','2026-09-20',-3))).revenue, 0)
  await ingestOrder('test', 'generic', { ...order, externalId: 'unknown-net', financialsKnown: false }, {})
  const unknown = await getSummary('test', buildRange('2026-09-20','2026-09-20',-3))
  assert.equal(unknown.revenue, null); assert.equal(unknown.roas, null); assert.equal(unknown.unknownFinancials, 1)
  console.log('PASS: late webhooks, partial items, paid-date timezone, revenue allocation, unknown attribution, queue dedupe, missing tokens and refunds.')
}
main().catch(e => { console.error(e); process.exitCode = 1 }).finally(() => { db.close(); fs.rmSync(temp, { recursive: true, force: true }) })
