const { chromium } = require('playwright')
const { spawn } = require('node:child_process')
const { randomBytes } = require('node:crypto')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const assert = require('node:assert/strict')
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'tracking-ui-'))
const password = randomBytes(24).toString('hex')
const server = spawn(process.execPath, ['node_modules/next/dist/bin/next', 'start', '-p', '3218', '-H', '127.0.0.1'], { env: { ...process.env, PANEL_PASSWORD: password, PANEL_USER: 'test', TURSO_DATABASE_URL: 'file:' + path.join(temp, 'ui.db') }, stdio: 'inherit' })
let browser
async function main() {
  for (let i = 0; i < 20; i++) { try { const r = await fetch('http://127.0.0.1:3218/dashboard', { signal: AbortSignal.timeout(1000) }); if (r.status === 401) break } catch {} await new Promise(r => setTimeout(r, 250)) }
  assert.equal((await fetch('http://127.0.0.1:3218/api/orders', { signal: AbortSignal.timeout(2000) })).status, 401)
  assert.equal((await fetch('http://127.0.0.1:3218/api/cron/flush-capi', { signal: AbortSignal.timeout(2000) })).status, 401)
  browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] })
  const context = await browser.newContext({ httpCredentials: { username: 'test', password } })
  const page = await context.newPage()
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.setViewportSize({ width: 1440, height: 1100 })
  await page.goto('http://127.0.0.1:3218/dashboard')
  await page.getByRole('button', { name: 'Ver demonstração', exact: true }).click()
  await page.getByRole('status').filter({ hasText: 'DEMONSTRAÇÃO' }).waitFor()
  fs.mkdirSync('docs/previews', { recursive: true })
  await page.screenshot({ path: 'docs/previews/dashboard-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 400, height: 860 })
  await page.screenshot({ path: 'docs/previews/dashboard-mobile.png', fullPage: true })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await page.getByRole('button', { name: 'Vendas aprovadas' }).click()
  assert.equal(await page.getByRole('button', { name: 'Vendas aprovadas' }).getAttribute('aria-expanded'), 'false')
  await page.reload()
  await page.getByRole('button', { name: 'Ver demonstração', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Vendas aprovadas' }).getAttribute('aria-expanded'), 'false')
  assert.deepEqual(errors, [])
  console.log('PASS: auth, closed cron, demo, mobile width, persistent collapse, no browser errors.')
}
main().catch(e => { console.error(e); process.exitCode = 1 }).finally(async () => { if (browser) await browser.close(); if (server.exitCode === null) { server.kill(); await new Promise(r => server.once('exit', r)) } fs.rmSync(temp, { recursive: true, force: true }) })
